import { createAppClient, type AppClient } from '../../integrations/http/api-client';
export type DashboardPriority = { key: string; title: string; detail: string; level: string; courseId?: string; studentId?: string };
export type DashboardTodayItem = { key: string; kind: 'task' | 'event'; title: string; detail?: string; startsAt?: string };
export type DashboardAccessSegment = { key: string; label: string; students: number; tone: 'success' | 'warning' | 'risk' };
export type DashboardAccessSnapshot = { date: string; totalStudents: number; recentStudents: number; lowAccessStudents: number; staleStudents: number; neverAccessedStudents: number; studentsAtRisk: number };
export type DashboardCoursePendingSummary = { courseId: string; courseName: string; pendingCorrectionActivities: number; pendingCorrectionSubmissions: number; pendingSubmissionActivities: number; pendingSubmissions: number; studentsAwaitingCorrection: number; studentsWithPendingSubmissions: number; overdueSubmissions: number; isTruncated: boolean; warning?: string };
export type DashboardActivity = { key: string; title: string; detail: string; occurredAt?: string; courseId?: string; studentId?: string };
export type DashboardResponse = { data: { summary: { activeCourses: number; pendingDeliveries: number; awaitingGrading: number; studentsAtRisk: number; studentsNeedingAttention: number; todayEvents?: number | null; todayTasks?: number | null; activitiesToReview?: number | null; activeNormalStudents?: number | null; pendingSubmissionAssignments?: number | null; pendingCorrectionAssignments?: number | null; newAtRiskThisWeek?: number | null; activeStudents?: number | null; neverAccessedStudents?: number | null }; priorities: DashboardPriority[]; activitiesToReview: DashboardPriority[]; recentActivity: DashboardActivity[]; connectionRef?: string; warnings: string[]; week?: 'current' | 'last'; weekStartsAt?: string; weekEndsAt?: string }; meta: { generatedAt: string; connectionRef?: string } };
export type DashboardSummaryMetric = { data: { summary: DashboardResponse['data']['summary']; warnings: string[] }; meta: { generatedAt: string; connectionRef?: string } };
export type DashboardPendingMetric = { data: { summary: DashboardResponse['data']['summary']; priorities: DashboardPriority[]; activitiesToReview: DashboardPriority[]; courseSummaries: DashboardCoursePendingSummary[]; todayItems: DashboardTodayItem[]; warnings: string[]; isRefreshing?: boolean; coursesInScope?: number; coursesAnalyzed?: number; snapshotGeneratedAt?: string | null }; meta: { generatedAt: string; connectionRef?: string } };
export type DashboardAccessMetric = { data: { summary: DashboardResponse['data']['summary']; segments: DashboardAccessSegment[]; snapshots?: DashboardAccessSnapshot[]; warnings: string[] }; meta: { generatedAt: string; connectionRef?: string } };
export type DashboardCoursesMetric = { data: { courses: Array<{ connectionRef: string; courseId: string; shortName?: string; fullName: string; displayName?: string; categoryName?: string; startDate?: string; endDate?: string; visible?: boolean; viewUrl?: string; courseImage?: string; progress?: number; lastAccessAt?: string }>; warnings: string[] }; meta: { generatedAt: string; connectionRef?: string } };
export const createDashboardGateway = (client: AppClient = createAppClient()) => ({
  get: (connectionRef?: string, courseId?: string, activityOnly = false, week: 'current' | 'last' = 'current') => { const query = new URLSearchParams(); if (connectionRef) query.set('connectionRef', connectionRef); if (courseId) query.set('courseId', courseId); if (activityOnly) query.set('activityOnly', 'true'); if (week !== 'current') query.set('week', week); const suffix = query.toString() ? `?${query}` : ''; return client.get<DashboardResponse>(`/api/dashboard${suffix}`); },
  getMetric: <T extends DashboardSummaryMetric | DashboardPendingMetric | DashboardAccessMetric | DashboardCoursesMetric>(metric: 'summary' | 'pending' | 'access' | 'courses', connectionRef?: string, force = false) => { const query = new URLSearchParams(); if (connectionRef) query.set('connectionRef', connectionRef); if (force) query.set('refresh', 'true'); const suffix = query.toString() ? `?${query}` : ''; return client.get<T>(`/api/dashboard/${metric}${suffix}`); },
});
export const dashboardGateway = createDashboardGateway();


