import { FormEvent, useEffect, useState } from 'react';
import { Activity, KeyRound, RotateCcw, ShieldAlert } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { passwordGateway, type AdminMetrics, type PortalAccount } from './password-gateway';

export function ChangePasswordCard() {
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [message, setMessage] = useState(''); const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(''); if (newPassword.length < 8) return setMessage('A nova senha deve ter pelo menos 8 caracteres.'); if (newPassword !== confirmation) return setMessage('As novas senhas não coincidem.'); setPending(true); try { await passwordGateway.change(currentPassword, newPassword); setCurrentPassword(''); setNewPassword(''); setConfirmation(''); setMessage('Senha alterada com sucesso.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível alterar a senha.'); } finally { setPending(false); } };
  return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><KeyRound className="h-5 w-5" />Senha</CardTitle><CardDescription>Altere a senha da sua conta Claris. Use ao menos 8 caracteres.</CardDescription></CardHeader><CardContent><form className="max-w-lg space-y-4" onSubmit={submit}><div className="space-y-2"><Label htmlFor="current-password">Senha atual</Label><Input id="current-password" type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} autoComplete="current-password" required /></div><div className="space-y-2"><Label htmlFor="new-password">Nova senha</Label><Input id="new-password" type="password" minLength={8} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} autoComplete="new-password" required /></div><div className="space-y-2"><Label htmlFor="confirm-new-password">Confirmar nova senha</Label><Input id="confirm-new-password" type="password" minLength={8} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="new-password" required /></div>{message && <p className="text-sm" role="status">{message}</p>}<Button type="submit" disabled={pending}>{pending ? 'Alterando…' : 'Alterar senha'}</Button></form></CardContent></Card>;
}

export function AdminPasswordResetCard() {
  const [accounts, setAccounts] = useState<PortalAccount[]>([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [pendingId, setPendingId] = useState<string | null>(null);
  useEffect(() => { passwordGateway.listAccounts().then((result) => setAccounts(result.accounts)).catch((error) => setMessage(error instanceof Error ? error.message : 'Não foi possível carregar os usuários.')).finally(() => setLoading(false)); }, []);
  const reset = async (account: PortalAccount) => { if (!window.confirm(`Redefinir a senha de ${account.name} para a senha padrão configurada?`)) return; setMessage(''); setPendingId(account.id); try { const result = await passwordGateway.resetToDefault(account.id); setMessage(result.message ?? 'Senha redefinida.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível redefinir a senha.'); } finally { setPendingId(null); } };
  return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><ShieldAlert className="h-5 w-5" />Recuperação de senha</CardTitle><CardDescription>Redefina a senha de uma conta para a senha padrão configurada no servidor. Informe essa senha ao usuário por um canal seguro.</CardDescription></CardHeader><CardContent className="space-y-3">{message && <p className="text-sm" role="status">{message}</p>}{loading ? <p className="text-sm text-muted-foreground">Carregando usuários…</p> : <div className="divide-y rounded-md border">{accounts.map((account) => <div key={account.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><p className="font-medium">{account.name}</p><p className="text-sm text-muted-foreground">{account.email}</p></div><Button variant="outline" size="sm" disabled={pendingId === account.id} onClick={() => reset(account)}><RotateCcw className="mr-2 h-4 w-4" />{pendingId === account.id ? 'Redefinindo…' : 'Redefinir senha'}</Button></div>)}</div>}</CardContent></Card>;
}

export function AdminMetricsCard() {
  const [metrics, setMetrics] = useState<AdminMetrics | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); setMessage(''); passwordGateway.metrics().then(setMetrics).catch((error) => setMessage(error instanceof Error ? error.message : 'Não foi possível carregar as métricas.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const errorRate = metrics && metrics.totalRequests > 0 ? ((metrics.failedRequests / metrics.totalRequests) * 100).toFixed(1) : '0.0';
  return <Card><CardHeader className="flex-row items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2 text-lg"><Activity className="h-5 w-5" />Desempenho e auditoria</CardTitle><CardDescription>Últimos 7 dias. Registra rota, status, duração e código técnico — nunca conteúdo das requisições ou credenciais.</CardDescription></div><Button variant="outline" size="sm" onClick={load} disabled={loading}>Atualizar</Button></CardHeader><CardContent className="space-y-5">{message && <p className="text-sm" role="status">{message}</p>}{metrics?.warnings?.map((warning) => <p className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100" role="status" key={warning}>{warning}</p>)}{loading ? <p className="text-sm text-muted-foreground">Carregando métricas…</p> : metrics && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Requisições" value={metrics.totalRequests} /><Metric label="Erros" value={metrics.failedRequests} tone={metrics.failedRequests > 0 ? 'text-destructive' : undefined} /><Metric label="Taxa de erro" value={`${errorRate}%`} tone={Number(errorRate) > 3 ? 'text-destructive' : undefined} /><Metric label="Duração média" value={`${Math.round(metrics.averageDurationMs)} ms`} /></div><div className="grid gap-5 xl:grid-cols-2"><div><h3 className="mb-2 text-sm font-medium">Rotas mais acessadas</h3><MetricTable headers={['Rota', 'Req.', 'Erros', 'Média']} rows={metrics.endpoints.map((item) => [<span className="font-mono text-xs" key="route">{item.method} {item.endpoint}</span>, item.requests, item.errors, `${Math.round(item.averageDurationMs)} ms`])} empty="Ainda não há acessos registrados." /></div><div><h3 className="mb-2 text-sm font-medium">Tools Moodle</h3><MetricTable headers={['Tool', 'Chamadas', 'Erros', 'Média']} rows={metrics.tools.map((item) => [<span className="font-mono text-xs" key="tool">{item.toolName}</span>, item.invocations, item.errors, `${Math.round(item.averageDurationMs)} ms`])} empty="Ainda não há auditorias de tools no período." /></div></div><div><h3 className="mb-2 text-sm font-medium">Erros recentes</h3><MetricTable headers={['Quando', 'Origem', 'Operação', 'Código']} rows={metrics.errors.map((item) => [new Date(item.occurredAt).toLocaleString('pt-BR'), item.source, <span className="font-mono text-xs" key="operation">{item.operation}</span>, item.code])} empty="Nenhum erro no período." /></div></>}</CardContent></Card>;
}

function Metric({ label, value, tone }: { label: string; value: string | number; tone?: string }) { return <div className="rounded-lg border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 text-xl font-semibold ${tone ?? ''}`}>{value}</p></div>; }
function MetricTable({ headers, rows, empty }: { headers: string[]; rows: (string | number | React.ReactNode)[][]; empty: string }) { return rows.length === 0 ? <p className="rounded-md border p-3 text-sm text-muted-foreground">{empty}</p> : <div className="max-h-64 overflow-auto rounded-md border"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-muted text-xs text-muted-foreground"><tr>{headers.map((header) => <th className="p-2 font-medium" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr className="border-t" key={rowIndex}>{row.map((value, index) => <td className="p-2" key={index}>{value}</td>)}</tr>)}</tbody></table></div>; }
