import { FormEvent, useEffect, useState } from 'react';
import { KeyRound, RotateCcw, ShieldAlert } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { passwordGateway, type PortalAccount } from './password-gateway';

export function ChangePasswordCard() {
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [message, setMessage] = useState(''); const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(''); if (newPassword.length < 8) return setMessage('A nova senha deve ter pelo menos 8 caracteres.'); if (newPassword !== confirmation) return setMessage('As novas senhas não coincidem.'); setPending(true); try { await passwordGateway.change(currentPassword, newPassword); setCurrentPassword(''); setNewPassword(''); setConfirmation(''); setMessage('Senha alterada com sucesso.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível alterar a senha.'); } finally { setPending(false); } };
  return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><KeyRound className="h-5 w-5" />Senha</CardTitle><CardDescription>Altere a senha da sua conta Claris. Use ao menos 8 caracteres.</CardDescription></CardHeader><CardContent><form className="max-w-lg space-y-4" onSubmit={submit}><div className="space-y-2"><Label htmlFor="current-password">Senha atual</Label><Input id="current-password" type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} autoComplete="current-password" required /></div><div className="space-y-2"><Label htmlFor="new-password">Nova senha</Label><Input id="new-password" type="password" minLength={8} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} autoComplete="new-password" required /></div><div className="space-y-2"><Label htmlFor="confirm-new-password">Confirmar nova senha</Label><Input id="confirm-new-password" type="password" minLength={8} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="new-password" required /></div>{message && <p className="text-sm" role="status">{message}</p>}<Button type="submit" disabled={pending}>{pending ? 'Alterando…' : 'Alterar senha'}</Button></form></CardContent></Card>;
}

export function AdminPasswordResetCard() {
  const [accounts, setAccounts] = useState<PortalAccount[]>([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [pendingId, setPendingId] = useState<string | null>(null);
  useEffect(() => { passwordGateway.listAccounts().then((result) => setAccounts(result.accounts)).catch((error) => setMessage(error instanceof Error ? error.message : 'Não foi possível carregar os usuários.')).finally(() => setLoading(false)); }, []);
  const reset = async (account: PortalAccount) => { if (!window.confirm(`Redefinir a senha de ${account.name} para a senha padrão configurada?`)) return; setMessage(''); setPendingId(account.id); try { const result = await passwordGateway.resetToDefault(account.id); setMessage(result.message ?? 'Senha redefinida.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível redefinir a senha.'); } finally { setPendingId(null); } };
  return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><ShieldAlert className="h-5 w-5" />Recuperação de senha</CardTitle><CardDescription>Redefina a senha de uma conta para a senha padrão configurada no servidor. Informe essa senha ao usuário por um canal seguro.</CardDescription></CardHeader><CardContent className="space-y-3">{message && <p className="text-sm" role="status">{message}</p>}{loading ? <p className="text-sm text-muted-foreground">Carregando usuários…</p> : <div className="divide-y rounded-md border">{accounts.map((account) => <div key={account.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><p className="font-medium">{account.name}</p><p className="text-sm text-muted-foreground">{account.email}</p></div><Button variant="outline" size="sm" disabled={pendingId === account.id} onClick={() => reset(account)}><RotateCcw className="mr-2 h-4 w-4" />{pendingId === account.id ? 'Redefinindo…' : 'Redefinir senha'}</Button></div>)}</div>}</CardContent></Card>;
}
