import { useQuery } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { Card, CardContent } from '../../components/ui/card';
import { Skeleton } from '../../components/ui/skeleton';
import { Pagination } from '../../components/ui/pagination';
import { RiskBadge } from './components/RiskBadge';
import { EnrollmentBadge } from './components/EnrollmentBadge';
import { studentsGateway } from './students-gateway';
export function StudentsPage() { const [params, setParams] = useSearchParams(); const connectionRef = params.get('connectionRef'); const courseId = params.get('courseId'); const page = Number(params.get('page') ?? 1); const query = useQuery({ queryKey: ['portal','students',connectionRef,courseId,page], queryFn: () => { if (!connectionRef || !courseId) return Promise.reject(new Error("Selecione um curso.")); return studentsGateway.byCourse(connectionRef, courseId, page); }, enabled: !!connectionRef && !!courseId }); const totalPages = query.data ? (query.data.meta.total ? Math.max(1, Math.ceil(query.data.meta.total / query.data.meta.pageSize)) : query.data.meta.hasMore ? page + 1 : page) : 1; return <main className="content-frame students-page"><header className="page-heading"><div><p className="eyebrow">OPERACIONAL</p><h1>Alunos</h1><p>Consulte alunos, acessos, matrículas e risco de forma somente leitura.</p></div>{query.data && <span className="freshness">Atualizado em {new Date(query.data.meta.generatedAt).toLocaleString('pt-BR')}</span>}</header>{(!connectionRef || !courseId) && <Card><CardContent><p>Selecione um curso no topo da página para listar os alunos.</p></CardContent></Card>}{query.isPending && connectionRef && courseId && <div className="student-grid"><Skeleton /><Skeleton /></div>}{query.isError && <Card><CardContent><p role="alert">Não foi possível carregar os alunos.</p></CardContent></Card>}{query.isSuccess && query.data.data.length === 0 && <Card><CardContent><p>Nenhum aluno encontrado.</p></CardContent></Card>}{query.isSuccess && <><section className="student-grid" aria-label="Alunos">{query.data.data.map(student => <Card key={`${student.connectionRef}:${student.studentId}`}><CardContent><div className="student-card-heading"><div><h2>{student.name}</h2><p>{student.email ?? 'Email não informado'}</p></div><RiskBadge level={student.risk} /></div><div className="student-card-meta"><EnrollmentBadge status={student.suspended ? 'suspenso' : 'ativo'} /><span>{student.connectionRef}</span></div><Link className="ui-button ui-button-outline ui-button-sm" to={`/alunos/${encodeURIComponent(student.connectionRef)}/${encodeURIComponent(courseId!)}/${encodeURIComponent(student.studentId)}`}>Abrir perfil</Link></CardContent></Card>)}</section><Pagination page={page} totalPages={totalPages} onPageChange={next => setParams({ ...(connectionRef ? { connectionRef } : {}), ...(courseId ? { courseId } : {}), page: String(next) })} /></>}</main>; }
