using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoodleConnector.Infrastructure;

namespace MoodleConnector.Presentation.Endpoints;

/// <summary>Professional v1 surface. Legacy list/create routes stay available during the compatibility window.</summary>
internal static class ProfessionalPlannerEndpoints
{
    public static void Map(WebApplication app, string rateLimit)
    {
        app.MapGet("/api/tasks/{id:guid}", async (Guid id, HttpContext http, ConnectorDbContext db, CancellationToken ct) =>
        {
            var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return Results.Unauthorized();
            var item = await new ProfessionalPlannerService(db).GetTaskAsync(identity.Id, id, ct); return item is null ? Results.NotFound() : Results.Ok(new AppEnvelope<TaskDetailDto>(item, new(DateTimeOffset.UtcNow, null)));
        }).RequireRateLimiting(rateLimit);

        app.MapGet("/api/tasks", async (HttpContext http, ConnectorDbContext db, int page = 1, int pageSize = 20, string? search = null, string? status = null, string? priority = null, Guid? participantId = null, string? tag = null, string? referenceType = null, string? referenceId = null, CancellationToken ct = default) =>
        {
            var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return Results.Unauthorized(); page = Math.Max(1, page); pageSize = Math.Clamp(pageSize, 1, 100);
            var result = await new ProfessionalPlannerService(db).ListTasksAsync(identity.Id, page, pageSize, search, status, priority, participantId, tag, referenceType, referenceId, ct);
            return Results.Ok(new AppListEnvelope<TaskListItemDto>(result.Items, new(page, pageSize, result.Items.Count, page * pageSize < result.Total, DateTimeOffset.UtcNow, null, null, result.Total)));
        }).RequireRateLimiting(rateLimit);

        app.MapPost("/api/tasks", async (HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, TaskProfessionalInput input, CancellationToken ct) =>
        {
            var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid();
            return await Handle(async () => Results.Created("/api/tasks", new AppEnvelope<TaskDetailDto>(await new ProfessionalPlannerService(db).CreateTaskAsync(identity.Id, identity.Id, input, ct), new(DateTimeOffset.UtcNow, null))));
        }).RequireRateLimiting(rateLimit);

        app.MapDelete("/api/tasks", async (HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, [FromBody] TaskBulkDeleteInput? input, CancellationToken ct) =>
        {
            var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid();
            var ids = input?.Ids?.Where(x => x != Guid.Empty).Distinct().Take(100).ToArray() ?? [];
            if (ids.Length == 0) return Results.BadRequest(new { error = new { code = "invalid_task_ids", message = "Informe ao menos uma Task." } });
            var tasks = await db.Tasks.Where(x => x.OwnerId == identity.Id && ids.Contains(x.Id)).ToListAsync(ct); db.Tasks.RemoveRange(tasks); await db.SaveChangesAsync(ct);
            return Results.Ok(new AppEnvelope<TaskBulkDeleteResult>(new(ids.Length, tasks.Count), new(DateTimeOffset.UtcNow, null)));
        }).RequireRateLimiting(rateLimit);

        app.MapPatch("/api/tasks/{id:guid}", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, TaskProfessionalInput input, CancellationToken ct) =>
        {
            var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid();
            return await Handle(async () => Results.Ok(new AppEnvelope<TaskDetailDto>(await new ProfessionalPlannerService(db).UpdateTaskAsync(identity.Id, identity.Id, id, input, ct), new(DateTimeOffset.UtcNow, null))));
        }).RequireRateLimiting(rateLimit);

        app.MapDelete("/api/tasks/{id:guid}", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CancellationToken ct) =>
        {
            var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid();
            return await Handle(async () => { await new ProfessionalPlannerService(db).DeleteTaskAsync(identity.Id, id, ct); return Results.NoContent(); });
        }).RequireRateLimiting(rateLimit);

        app.MapPost("/api/tasks/{id:guid}/complete", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, long? expectedVersion, CancellationToken ct) =>
        {
            var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid();
            return await Handle(async () => Results.Ok(new AppEnvelope<TaskDetailDto>(await new ProfessionalPlannerService(db).CompleteAsync(identity.Id, identity.Id, id, true, expectedVersion, ct), new(DateTimeOffset.UtcNow, null))));
        }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/tasks/{id:guid}/reopen", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, long? expectedVersion, CancellationToken ct) =>
        {
            var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid();
            return await Handle(async () => Results.Ok(new AppEnvelope<TaskDetailDto>(await new ProfessionalPlannerService(db).CompleteAsync(identity.Id, identity.Id, id, false, expectedVersion, ct), new(DateTimeOffset.UtcNow, null))));
        }).RequireRateLimiting(rateLimit);
        app.MapGet("/api/tasks/{id:guid}/subtasks", async (Guid id, HttpContext http, ConnectorDbContext db, CancellationToken ct) => { var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return Results.Unauthorized(); var task = await new ProfessionalPlannerService(db).GetTaskAsync(identity.Id, id, ct); return task is null ? Results.NotFound() : Results.Ok(new AppEnvelope<IReadOnlyList<TaskListItemDto>>(task.Subtasks, new(DateTimeOffset.UtcNow, null))); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/tasks/{id:guid}/subtasks", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, TaskProfessionalInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => Results.Created($"/api/tasks/{id}/subtasks", new AppEnvelope<TaskDetailDto>(await new ProfessionalPlannerService(db).CreateTaskAsync(identity.Id, identity.Id, input with { ParentTaskId = id }, ct), new(DateTimeOffset.UtcNow, null)))); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/tasks/{id:guid}/comments", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CommentInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).AddCommentAsync(identity.Id, identity.Id, id, input.Content, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapPatch("/api/tasks/{id:guid}/comments/{commentId:guid}", async (Guid id, Guid commentId, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CommentInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).EditCommentAsync(identity.Id, identity.Id, id, commentId, input.Content, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/tasks/{id:guid}/participants", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, TaskParticipantInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).AddParticipantAsync(identity.Id, identity.Id, id, input, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapDelete("/api/tasks/{id:guid}/participants/{userId:guid}", async (Guid id, Guid userId, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).RemoveParticipantAsync(identity.Id, identity.Id, id, userId, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/tasks/{id:guid}/references", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, TaskReferenceV2Input input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).AddReferenceAsync(identity.Id, identity.Id, id, input, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapDelete("/api/tasks/{id:guid}/references/{referenceId:guid}", async (Guid id, Guid referenceId, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).RemoveReferenceAsync(identity.Id, identity.Id, id, referenceId, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/tasks/{id:guid}/tags", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, TagInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).AddTagAsync(identity.Id, identity.Id, id, input.Value, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapDelete("/api/tasks/{id:guid}/tags/{value}", async (Guid id, string value, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).RemoveTagAsync(identity.Id, identity.Id, id, value, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapGet("/api/tasks/{id:guid}/activity", async (Guid id, HttpContext http, ConnectorDbContext db, int page = 1, int pageSize = 30, CancellationToken ct = default) => { var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return Results.Unauthorized(); return await Handle(async () => Results.Ok(new AppEnvelope<TaskTimelinePageDto>(await new ProfessionalPlannerService(db).TimelineAsync(identity.Id, id, Math.Max(1, page), Math.Clamp(pageSize, 1, 100), ct), new(DateTimeOffset.UtcNow, null)))); }).RequireRateLimiting(rateLimit);
        app.MapGet("/api/tasks/{id:guid}/dependencies", async (Guid id, HttpContext http, ConnectorDbContext db, CancellationToken ct) => { var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return Results.Unauthorized(); var task = await new ProfessionalPlannerService(db).GetTaskAsync(identity.Id, id, ct); return task is null ? Results.NotFound() : Results.Ok(new AppEnvelope<object>(new { dependsOn = task.DependsOn, blocks = task.Blocks }, new(DateTimeOffset.UtcNow, null))); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/tasks/{id:guid}/dependencies", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, DependencyInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).AddDependencyAsync(identity.Id, identity.Id, id, input.DependsOnTaskId, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapDelete("/api/tasks/{id:guid}/dependencies/{dependsOnId:guid}", async (Guid id, Guid dependsOnId, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).RemoveDependencyAsync(identity.Id, identity.Id, id, dependsOnId, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapGet("/api/tasks/{id:guid}/events", async (Guid id, HttpContext http, ConnectorDbContext db, CancellationToken ct) => { var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return Results.Unauthorized(); return await Handle(async () => Results.Ok(new AppEnvelope<IReadOnlyList<TaskEventLinkDto>>(await new ProfessionalPlannerService(db).TaskLinksAsync(identity.Id, id, ct), new(DateTimeOffset.UtcNow, null)))); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/tasks/{id:guid}/events", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, TaskEventLinkInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.AgendaManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { var service = new ProfessionalPlannerService(db); if (string.Equals(input.Mode, "create", StringComparison.OrdinalIgnoreCase)) { if (input.StartAt is null) throw new ArgumentException("StartAt é obrigatório no modo create."); return Results.Created("/api/agenda", new AppEnvelope<EventDto>(await service.CreateEventFromTaskAsync(identity.Id, identity.Id, id, new(input.StartAt.Value, input.EndAt, input.Recurrence, input.Relation), ct), new(DateTimeOffset.UtcNow, null))); } return Results.Created($"/api/tasks/{id}/events", new AppEnvelope<TaskEventLinkDto>(await service.LinkAsync(identity.Id, identity.Id, id, input, ct), new(DateTimeOffset.UtcNow, null))); }); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/tasks/{id:guid}/events/create", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CreateEventFromTaskInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.AgendaManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => Results.Created("/api/agenda", new AppEnvelope<EventDto>(await new ProfessionalPlannerService(db).CreateEventFromTaskAsync(identity.Id, identity.Id, id, input, ct), new(DateTimeOffset.UtcNow, null)))); }).RequireRateLimiting(rateLimit);
        app.MapDelete("/api/tasks/{id:guid}/events/{linkId:guid}", async (Guid id, Guid linkId, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).UnlinkAsync(identity.Id, identity.Id, id, linkId, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);

        app.MapGet("/api/agenda/{id:guid}", async (Guid id, HttpContext http, ConnectorDbContext db, CancellationToken ct) => { var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return Results.Unauthorized(); var e = await new ProfessionalPlannerService(db).GetEventAsync(identity.Id, id, ct); return e is null ? Results.NotFound() : Results.Ok(new AppEnvelope<EventDto>(e, new(DateTimeOffset.UtcNow, null))); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/agenda/professional", async (HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, EventProfessionalInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.AgendaManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => Results.Created("/api/agenda", new AppEnvelope<EventDto>(await new ProfessionalPlannerService(db).CreateEventAsync(identity.Id, identity.Id, input, ct), new(DateTimeOffset.UtcNow, null)))); }).RequireRateLimiting(rateLimit);
        app.MapPatch("/api/agenda/{id:guid}/professional", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, EventProfessionalInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.AgendaManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => Results.Ok(new AppEnvelope<EventDto>(await new ProfessionalPlannerService(db).UpdateEventAsync(identity.Id, identity.Id, id, input, ct), new(DateTimeOffset.UtcNow, null)))); }).RequireRateLimiting(rateLimit);
        app.MapGet("/api/agenda/occurrences", async (HttpContext http, ConnectorDbContext db, DateTimeOffset from, DateTimeOffset to, string? tag = null, Guid? taskId = null, string? referenceType = null, string? referenceId = null, Guid? tutorId = null, int page = 1, int pageSize = 100, CancellationToken ct = default) => { var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return Results.Unauthorized(); referenceType ??= tutorId is null ? null : "tutor"; referenceId ??= tutorId?.ToString(); return await Handle(async () => Results.Ok(new AppEnvelope<IReadOnlyList<EventOccurrenceDto>>(await new ProfessionalPlannerService(db).OccurrencesAsync(identity.Id, from, to, tag, taskId, ct, referenceType, referenceId, page, pageSize), new(DateTimeOffset.UtcNow, null)))); }).RequireRateLimiting(rateLimit);
        app.MapPut("/api/agenda/{id:guid}/occurrences/{originalStart}", async (Guid id, DateTimeOffset originalStart, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, OccurrenceOverrideInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.AgendaManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).OverrideOccurrenceAsync(identity.Id, id, originalStart, input, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapPatch("/api/agenda/{id:guid}/occurrences/{originalStart}", async (Guid id, DateTimeOffset originalStart, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, OccurrenceOverrideInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.AgendaManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).OverrideOccurrenceAsync(identity.Id, id, originalStart, input, ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapDelete("/api/agenda/{id:guid}/occurrences/{originalStart}", async (Guid id, DateTimeOffset originalStart, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.AgendaManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { await new ProfessionalPlannerService(db).OverrideOccurrenceAsync(identity.Id, id, originalStart, new OccurrenceOverrideInput(IsCancelled: true), ct); return Results.NoContent(); }); }).RequireRateLimiting(rateLimit);
        app.MapGet("/api/agenda/{id:guid}/tasks", async (Guid id, HttpContext http, ConnectorDbContext db, CancellationToken ct) => { var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return Results.Unauthorized(); return await Handle(async () => Results.Ok(new AppEnvelope<IReadOnlyList<TaskEventLinkDto>>(await new ProfessionalPlannerService(db).EventLinksAsync(identity.Id, id, ct), new(DateTimeOffset.UtcNow, null)))); }).RequireRateLimiting(rateLimit);
        app.MapPost("/api/agenda/{id:guid}/tasks", async (Guid id, HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, CreateTaskFromEventInput input, CancellationToken ct) => { var identity = await WriteIdentity(http, db, xsrf, AppPermissionCatalog.TasksManage, ct); if (identity is null) return Results.Forbid(); return await Handle(async () => { var service = new ProfessionalPlannerService(db); if (string.Equals(input.Mode, "link", StringComparison.OrdinalIgnoreCase)) { if (input.TaskId is null || input.TaskId == Guid.Empty) throw new ArgumentException("TaskId é obrigatório no modo link."); var link = await service.LinkAsync(identity.Id, identity.Id, input.TaskId.Value, new(id, null, input.Relation), ct); return Results.Created($"/api/agenda/{id}/tasks", new AppEnvelope<TaskEventLinkDto>(link, new(DateTimeOffset.UtcNow, null))); } return Results.Created("/api/tasks", new AppEnvelope<TaskDetailDto>(await service.CreateTaskFromEventAsync(identity.Id, identity.Id, id, input, ct), new(DateTimeOffset.UtcNow, null))); }); }).RequireRateLimiting(rateLimit);
    }

    private static async Task<AppIdentity?> WriteIdentity(HttpContext http, ConnectorDbContext db, IAntiforgery xsrf, string permission, CancellationToken ct) { if (!PortalEndpointAuthorization.HasAppPermission(http, permission)) return null; var identity = await PortalEndpointAuthorization.ResolveAppIdentityAsync(http, db, ct); if (identity is null) return null; await xsrf.ValidateRequestAsync(http); return identity; }
    private static async Task<IResult> Handle(Func<Task<IResult>> action) { try { return await action(); } catch (KeyNotFoundException) { return Results.NotFound(); } catch (DbUpdateConcurrencyException ex) { return Results.Conflict(new { error = new { code = "optimistic_conflict", message = ex.Message } }); } catch (InvalidOperationException ex) { return Results.Conflict(new { error = new { code = "optimistic_conflict", message = ex.Message } }); } catch (ArgumentException ex) { return Results.BadRequest(new { error = new { code = "invalid_planner_input", message = ex.Message } }); } }
    public sealed record CommentInput(string Content);
    public sealed record TagInput(string Value);
}
