using System.ComponentModel;
using System.Text.Json;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;
using MoodleConnector.Application.Tools;
using MoodleConnector.Infrastructure;
using MoodleConnector.Presentation.Configuration;
using MoodleConnector.Presentation.Tools;

namespace MoodleConnector.Presentation.Tools.Portal;

/// <summary>MCP operations added by SPEC-0018 and SPEC-0023; all delegate to ProfessionalPlannerService.</summary>
[McpServerToolType]
public sealed class ProfessionalPlannerTools(ConnectorDbContext db, PortalMcpIdentityResolver identities)
{
    [McpServerTool(Name = "get_task_detail", Title = "Consultar detalhe de tarefa", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R1", Kind = "read", CanonicalOperation = "portal.tasks.detail", RequiredPlatformPermission = "tasks.manage", Evidence = "Lê uma Task profissional e seu contexto operacional.")]
    public async Task<CallToolResult> GetTaskAsync(Guid taskId, CancellationToken cancellationToken = default) => await Run(async (service, identity) => { var item = await service.GetTaskAsync(identity.Id, taskId, cancellationToken); return item is null ? Error<TaskDetailDto>("Task não encontrada.", "portal_task_not_found") : Ok(item, "Task encontrada."); }, cancellationToken);

    [McpServerTool(Name = "complete_task", Title = "Concluir tarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.complete", RequiredPlatformPermission = "tasks.manage", Evidence = "Conclui Task ou subtarefa e registra Activity.")]
    public Task<CallToolResult> CompleteTaskAsync(Guid taskId, long? expectedVersion = null, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.CompleteAsync(i.Id, i.Id, taskId, true, expectedVersion, cancellationToken), "Task concluída."), cancellationToken);

    [McpServerTool(Name = "reopen_task", Title = "Reabrir tarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.reopen", RequiredPlatformPermission = "tasks.manage", Evidence = "Reabre Task e registra Activity.")]
    public Task<CallToolResult> ReopenTaskAsync(Guid taskId, long? expectedVersion = null, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.CompleteAsync(i.Id, i.Id, taskId, false, expectedVersion, cancellationToken), "Task reaberta."), cancellationToken);

    [McpServerTool(Name = "create_task_subtask", Title = "Criar subtarefa", ReadOnly = false, Destructive = false, Idempotent = false, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.subtask.create", RequiredPlatformPermission = "tasks.manage", Evidence = "Cria uma Task filha e registra o fato na Activity da raiz.")]
    public Task<CallToolResult> CreateSubtaskAsync(Guid parentTaskId, string title, string? description = null, string? priority = null, DateTimeOffset? dueAt = null, Guid? ownerId = null, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.CreateTaskAsync(i.Id, i.Id, new TaskProfessionalInput(title, description, Priority: priority, DueAt: dueAt, ParentTaskId: parentTaskId, Participants: ownerId is null ? null : [new(ownerId.Value, "owner")]), cancellationToken), "Subtarefa criada."), cancellationToken);

    [McpServerTool(Name = "update_task_subtask", Title = "Editar subtarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.subtask.update", RequiredPlatformPermission = "tasks.manage", Evidence = "Edita somente uma Task filha da raiz informada, com concorrência otimista.")]
    public Task<CallToolResult> UpdateSubtaskAsync(Guid parentTaskId, Guid subtaskId, string? title = null, string? description = null, string? status = null, string? priority = null, DateTimeOffset? startAt = null, DateTimeOffset? dueAt = null, long? expectedVersion = null, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.UpdateSubtaskAsync(i.Id, i.Id, parentTaskId, subtaskId, new TaskProfessionalInput(title, description, status, priority, startAt, dueAt, ExpectedVersion: expectedVersion), cancellationToken), "Subtarefa atualizada."), cancellationToken);

    [McpServerTool(Name = "complete_task_subtask", Title = "Concluir subtarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.subtask.complete", RequiredPlatformPermission = "tasks.manage", Evidence = "Conclui ou reabre uma subtarefa e registra Activity na filha e na raiz.")]
    public Task<CallToolResult> CompleteSubtaskAsync(Guid parentTaskId, Guid subtaskId, bool complete = true, long? expectedVersion = null, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.CompleteSubtaskAsync(i.Id, i.Id, parentTaskId, subtaskId, complete, expectedVersion, cancellationToken), complete ? "Subtarefa concluída." : "Subtarefa reaberta."), cancellationToken);

    [McpServerTool(Name = "add_task_dependency", Title = "Adicionar dependência da tarefa", ReadOnly = false, Destructive = false, Idempotent = false, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.dependency.add", RequiredPlatformPermission = "tasks.manage", Evidence = "Adiciona bloqueio com rejeição de auto-dependência, duplicação e ciclos.")]
    public Task<CallToolResult> AddDependencyAsync(Guid taskId, Guid dependsOnTaskId, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.AddDependencyAsync(i.Id, i.Id, taskId, dependsOnTaskId, cancellationToken); return Ok((await s.GetTaskAsync(i.Id, taskId, cancellationToken))!, "Dependência adicionada."); }, cancellationToken);

    [McpServerTool(Name = "remove_task_dependency", Title = "Remover dependência da tarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.dependency.remove", RequiredPlatformPermission = "tasks.manage", Evidence = "Remove somente o bloqueio indicado e registra Activity.")]
    public Task<CallToolResult> RemoveDependencyAsync(Guid taskId, Guid dependsOnTaskId, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.RemoveDependencyAsync(i.Id, i.Id, taskId, dependsOnTaskId, cancellationToken); return Ok((await s.GetTaskAsync(i.Id, taskId, cancellationToken))!, "Dependência removida."); }, cancellationToken);

    [McpServerTool(Name = "add_task_collaborator", Title = "Adicionar participante à tarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.participant.add", RequiredPlatformPermission = "tasks.manage", Evidence = "Adiciona owner, collaborator ou watcher com auditoria.")]
    public Task<CallToolResult> AddCollaboratorAsync(Guid taskId, Guid userId, [Description("owner, collaborator ou watcher")] string role = "collaborator", CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.AddParticipantAsync(i.Id, i.Id, taskId, new(userId, role), cancellationToken); return Ok((await s.GetTaskAsync(i.Id, taskId, cancellationToken))!, "Participante atualizado."); }, cancellationToken);

    [McpServerTool(Name = "add_task_reference", Title = "Adicionar referência estruturada à tarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.reference.add", RequiredPlatformPermission = "tasks.manage", Evidence = "Adiciona referência acadêmica sem degradá-la a tag.")]
    public Task<CallToolResult> AddReferenceAsync(Guid taskId, string referenceType, string referenceId, string? referenceName = null, string? connectionRef = null, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.AddReferenceAsync(i.Id, i.Id, taskId, new(referenceType, referenceId, referenceName, connectionRef), cancellationToken); return Ok((await s.GetTaskAsync(i.Id, taskId, cancellationToken))!, "Referência adicionada."); }, cancellationToken);

    [McpServerTool(Name = "remove_task_reference", Title = "Remover referência da tarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.reference.remove", RequiredPlatformPermission = "tasks.manage", Evidence = "Remove referência estruturada sem afetar tags ou participantes.")]
    public Task<CallToolResult> RemoveReferenceAsync(Guid taskId, Guid referenceId, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.RemoveReferenceAsync(i.Id, i.Id, taskId, referenceId, cancellationToken); return Ok((await s.GetTaskAsync(i.Id, taskId, cancellationToken))!, "Referência removida."); }, cancellationToken);

    [McpServerTool(Name = "add_task_tag", Title = "Adicionar tag à tarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.tag.add", RequiredPlatformPermission = "tasks.manage", Evidence = "Adiciona classificação livre normalizada à Task.")]
    public Task<CallToolResult> AddTagAsync(Guid taskId, string tag, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.AddTagAsync(i.Id, i.Id, taskId, tag, cancellationToken); return Ok((await s.GetTaskAsync(i.Id, taskId, cancellationToken))!, "Tag adicionada."); }, cancellationToken);

    [McpServerTool(Name = "remove_task_tag", Title = "Remover tag da tarefa", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.tag.remove", RequiredPlatformPermission = "tasks.manage", Evidence = "Remove apenas a tag indicada da Task.")]
    public Task<CallToolResult> RemoveTagAsync(Guid taskId, string tag, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.RemoveTagAsync(i.Id, i.Id, taskId, tag, cancellationToken); return Ok((await s.GetTaskAsync(i.Id, taskId, cancellationToken))!, "Tag removida."); }, cancellationToken);

    [McpServerTool(Name = "add_task_comment", Title = "Comentar em tarefa", ReadOnly = false, Destructive = false, Idempotent = false, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskTimelinePageDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.comment.add", RequiredPlatformPermission = "tasks.manage", Evidence = "Adiciona comentário humano e Activity cumulativa.")]
    public Task<CallToolResult> AddCommentAsync(Guid taskId, string content, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.AddCommentAsync(i.Id, i.Id, taskId, content, cancellationToken); return Ok(await s.TimelineAsync(i.Id, taskId, 1, 30, cancellationToken), "Comentário adicionado."); }, cancellationToken);

    [McpServerTool(Name = "edit_task_comment", Title = "Editar comentário de tarefa", ReadOnly = false, Destructive = true, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskTimelinePageDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.comment.edit", RequiredPlatformPermission = "tasks.manage", Evidence = "Edita comentário humano preservando EditedAt e a Activity da Task.")]
    public Task<CallToolResult> EditCommentAsync(Guid taskId, Guid commentId, string content, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.EditCommentAsync(i.Id, i.Id, taskId, commentId, content, cancellationToken); return Ok(await s.TimelineAsync(i.Id, taskId, 1, 30, cancellationToken), "Comentário atualizado."); }, cancellationToken);

    [McpServerTool(Name = "list_task_activity", Title = "Ler histórico de tarefa", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskTimelinePageDto>))]
    [MoodleToolMetadata(Family = "portal-tasks", Classification = "R1", Kind = "read", CanonicalOperation = "portal.tasks.activity.list", RequiredPlatformPermission = "tasks.manage", Evidence = "Lê timeline paginada de comentários e fatos imutáveis.")]
    public Task<CallToolResult> ListActivityAsync(Guid taskId, int page = 1, int pageSize = 30, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.TimelineAsync(i.Id, taskId, Math.Max(1, page), Math.Clamp(pageSize, 1, 100), cancellationToken), "Histórico retornado."), cancellationToken);

    [McpServerTool(Name = "link_task_event", Title = "Vincular tarefa e Event", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskEventLinkDto>))]
    [MoodleToolMetadata(Family = "portal-planner", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.events.link", RequiredPlatformPermission = "tasks.manage", Evidence = "Relaciona explicitamente Task e série ou ocorrência de Event.")]
    public Task<CallToolResult> LinkEventAsync(Guid taskId, Guid eventId, DateTimeOffset? occurrenceStartAt = null, string relation = "related", CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.LinkAsync(i.Id, i.Id, taskId, new(eventId, occurrenceStartAt, relation), cancellationToken), "Event vinculado."), cancellationToken);

    [McpServerTool(Name = "unlink_task_event", Title = "Desvincular tarefa e Event", ReadOnly = false, Destructive = true, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<object>))]
    [MoodleToolMetadata(Family = "portal-planner", Classification = "R3", Kind = "destructive-write", CanonicalOperation = "portal.tasks.events.unlink", RequiredPlatformPermission = "tasks.manage", Evidence = "Remove apenas a relação explícita, sem alterar o ciclo de vida dos domínios.")]
    public Task<CallToolResult> UnlinkEventAsync(Guid taskId, Guid linkId, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.UnlinkAsync(i.Id, i.Id, taskId, linkId, cancellationToken); return Ok(new { removed = true }, "Event desvinculado."); }, cancellationToken);

    [McpServerTool(Name = "list_task_events", Title = "Listar Events da tarefa", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<IReadOnlyList<TaskEventLinkDto>>))]
    [MoodleToolMetadata(Family = "portal-planner", Classification = "R1", Kind = "read", CanonicalOperation = "portal.tasks.events.list", RequiredPlatformPermission = "tasks.manage", Evidence = "Consulta vínculos explícitos de uma Task.")]
    public Task<CallToolResult> ListTaskEventsAsync(Guid taskId, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.TaskLinksAsync(i.Id, taskId, cancellationToken), "Events da tarefa retornados."), cancellationToken);

    [McpServerTool(Name = "list_event_tasks", Title = "Listar Tasks do Event", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<IReadOnlyList<TaskEventLinkDto>>))]
    [MoodleToolMetadata(Family = "portal-planner", Classification = "R1", Kind = "read", CanonicalOperation = "portal.agenda.tasks.list", RequiredPlatformPermission = "agenda.manage", Evidence = "Consulta vínculos explícitos de um Event.")]
    public Task<CallToolResult> ListEventTasksAsync(Guid eventId, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.EventLinksAsync(i.Id, eventId, cancellationToken), "Tasks do Event retornadas."), cancellationToken);

    [McpServerTool(Name = "create_event_from_task", Title = "Criar Event a partir de Task", ReadOnly = false, Destructive = false, Idempotent = false, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<EventDto>))]
    [MoodleToolMetadata(Family = "portal-planner", Classification = "R2", Kind = "write", CanonicalOperation = "portal.tasks.events.create", RequiredPlatformPermission = "agenda.manage", Evidence = "Copia seletivamente título, descrição, tags e referências e cria vínculo explícito.")]
    public Task<CallToolResult> CreateEventFromTaskAsync(Guid taskId, DateTimeOffset startAt, DateTimeOffset? endAt = null, EventRecurrenceInput? recurrence = null, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.CreateEventFromTaskAsync(i.Id, i.Id, taskId, new(startAt, endAt, recurrence), cancellationToken), "Event criado a partir da Task."), cancellationToken);

    [McpServerTool(Name = "create_task_from_event", Title = "Criar Task a partir de Event", ReadOnly = false, Destructive = false, Idempotent = false, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<TaskDetailDto>))]
    [MoodleToolMetadata(Family = "portal-planner", Classification = "R2", Kind = "write", CanonicalOperation = "portal.agenda.tasks.create", RequiredPlatformPermission = "tasks.manage", Evidence = "Copia seletivamente título, descrição, tags e referências e cria vínculo explícito.")]
    public Task<CallToolResult> CreateTaskFromEventAsync(Guid eventId, DateTimeOffset? dueAt = null, DateTimeOffset? occurrenceStartAt = null, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.CreateTaskFromEventAsync(i.Id, i.Id, eventId, new(dueAt, OccurrenceStartAt: occurrenceStartAt), cancellationToken), "Task criada a partir do Event."), cancellationToken);

    [McpServerTool(Name = "list_agenda_occurrences", Title = "Listar ocorrências da agenda", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<IReadOnlyList<EventOccurrenceDto>>))]
    [MoodleToolMetadata(Family = "portal-agenda", Classification = "R1", Kind = "read", CanonicalOperation = "portal.agenda.occurrences.list", RequiredPlatformPermission = "agenda.manage", Evidence = "Expande somente ocorrências do intervalo solicitado.")]
    public Task<CallToolResult> ListOccurrencesAsync(DateTimeOffset from, DateTimeOffset to, string? tag = null, Guid? taskId = null, string? referenceType = null, string? referenceId = null, int page = 1, int pageSize = 100, CancellationToken cancellationToken = default) => Run(async (s, i) => Ok(await s.OccurrencesAsync(i.Id, from, to, tag, taskId, cancellationToken, referenceType, referenceId, page, pageSize), "Ocorrências retornadas."), cancellationToken);

    [McpServerTool(Name = "override_agenda_occurrence", Title = "Editar ocorrência do evento", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<object>))]
    [MoodleToolMetadata(Family = "portal-agenda", Classification = "R2", Kind = "write", CanonicalOperation = "portal.agenda.occurrence.update", RequiredPlatformPermission = "agenda.manage", Evidence = "Edita somente a ocorrência indicada e preserva a série original.")]
    public Task<CallToolResult> OverrideOccurrenceAsync(Guid eventId, DateTimeOffset originalStart, string? title = null, string? description = null, DateTimeOffset? startAt = null, DateTimeOffset? endAt = null, bool isCancelled = false, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.OverrideOccurrenceAsync(i.Id, eventId, originalStart, new(title, description, startAt, endAt, isCancelled), cancellationToken); return Ok(new { eventId, originalStart }, "Ocorrência atualizada."); }, cancellationToken);

    [McpServerTool(Name = "cancel_agenda_occurrence", Title = "Cancelar ocorrência do evento", ReadOnly = false, Destructive = false, Idempotent = true, OpenWorld = false, UseStructuredContent = true, OutputSchemaType = typeof(ToolResponse<object>))]
    [MoodleToolMetadata(Family = "portal-agenda", Classification = "R2", Kind = "write", CanonicalOperation = "portal.agenda.occurrence.cancel", RequiredPlatformPermission = "agenda.manage", Evidence = "Cancela apenas a ocorrência indicada por override, sem apagar a série.")]
    public Task<CallToolResult> CancelOccurrenceAsync(Guid eventId, DateTimeOffset originalStart, CancellationToken cancellationToken = default) => Run(async (s, i) => { await s.OverrideOccurrenceAsync(i.Id, eventId, originalStart, new OccurrenceOverrideInput(IsCancelled: true), cancellationToken); return Ok(new { eventId, originalStart, cancelled = true }, "Ocorrência cancelada."); }, cancellationToken);

    private async Task<CallToolResult> Run(Func<ProfessionalPlannerService, PortalMcpIdentity, Task<CallToolResult>> action, CancellationToken ct) { try { var identity = await identities.ResolveAsync(ct); return await action(new ProfessionalPlannerService(db), identity); } catch (KeyNotFoundException) { return Error<object>("Recurso não encontrado.", "portal_resource_not_found"); } catch (InvalidOperationException ex) { return Error<object>(ex.Message, "optimistic_conflict"); } catch (ArgumentException ex) { return Error<object>(ex.Message, "portal_planner_invalid_request"); } }
    private static CallToolResult Ok<T>(T value, string message) => new() { Content = [new TextContentBlock { Text = message }], StructuredContent = JsonSerializer.SerializeToElement(new ToolResponse<T>("ok", value, [], Guid.NewGuid().ToString("N"), DateTimeOffset.UtcNow, Message: message), new JsonSerializerOptions(JsonSerializerDefaults.Web)) };
    private static CallToolResult Error<T>(string message, string code) => ToolResultHelper.Error<T>(message, errorCode: code);
}
