import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { tasksGateway, type TaskInput, type TaskPriority, type TaskStatus } from './tasks-gateway';
const labels: Record<TaskStatus | TaskPriority, string> = { todo: 'A fazer', in_progress: 'Em andamento', done: 'Concluída', low: 'Baixa', medium: 'Média', high: 'Alta', urgent: 'Urgente' };
export function TasksPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['app', 'tasks'], queryFn: () => tasksGateway.list() });
  const [title, setTitle] = useState(''); const [priority, setPriority] = useState<TaskPriority>('medium');
  const create = useMutation({ mutationFn: (input: TaskInput) => tasksGateway.create(input), onSuccess: () => { setTitle(''); void client.invalidateQueries({ queryKey: ['app', 'tasks'] }); } });
  const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: TaskStatus }) => tasksGateway.update(id, { status }), onSuccess: () => void client.invalidateQueries({ queryKey: ['app', 'tasks'] }) });
  return <main className="content-frame"><header className="page-heading"><div><p className="eyebrow">GESTÃO</p><h1>Tarefas</h1><p>Organize tarefas operacionais separadas das atividades Moodle.</p></div>{query.data && <span className="freshness">Atualizado em {new Date(query.data.meta.generatedAt).toLocaleString('pt-BR')}</span>}</header><Card><CardHeader><CardTitle>Nova tarefa</CardTitle></CardHeader><CardContent><form onSubmit={e => { e.preventDefault(); if (title.trim()) create.mutate({ title, priority }); }} className="task-form"><input aria-label="Título da tarefa" value={title} onChange={e => setTitle(e.target.value)} placeholder="Ex.: acompanhar aluno" /><select aria-label="Prioridade" value={priority} onChange={e => setPriority(e.target.value as TaskPriority)}>{(['low', 'medium', 'high', 'urgent'] as TaskPriority[]).map(value => <option key={value} value={value}>{labels[value]}</option>)}</select><Button type="submit" disabled={create.isPending}>Adicionar</Button></form></CardContent></Card>{query.isPending && <p>Carregando tarefas…</p>}{query.isError && <Card><CardContent><p role="alert">Não foi possível carregar as tarefas.</p></CardContent></Card>}{query.data?.data.length === 0 && <Card><CardContent><p>Nenhuma tarefa criada ainda.</p></CardContent></Card>}<section className="student-grid" aria-label="Tarefas">{query.data?.data.map(task => <Card key={task.id}><CardContent><div className="student-card-heading"><div><h2>{task.title}</h2><p>{task.dueAt ? `Prazo ${new Date(task.dueAt).toLocaleDateString('pt-BR')}` : 'Sem prazo'}</p></div><Badge>{labels[task.priority]}</Badge></div><div className="student-card-meta"><span>{labels[task.status]}</span><select aria-label={`Status de ${task.title}`} value={task.status} onChange={e => update.mutate({ id: task.id, status: e.target.value as TaskStatus })}>{(['todo', 'in_progress', 'done'] as TaskStatus[]).map(value => <option key={value} value={value}>{labels[value]}</option>)}</select></div></CardContent></Card>)}</section></main>;
}

